version: '3'

services:
  portfolio:
    image: nye
    container_name: nye_countdown
    ports:
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.portfolio.rule=Host(`nye.olivierboeren.nl`)"
      - "traefik.frontend.entrypoints=http,https"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=le"
